services:
  frontend:
    build:
      context: ./frontend 
    ports:
      - "3000:80" 
    networks:
      - task-tracker-network
    depends_on:
      - backend 

  backend:
    build:
      context: ./backend  
    ports:
      - "5000:5000" 
    environment:
      - PORT=5000
    networks:
      - task-tracker-network

networks:
  task-tracker-network:
    driver: bridge
